sudo: required
services:
  - docker 

before_install: 
  - docker build -f -t ankurk/docker-react Dockerfile.dev .

  script:
  - docker run USERNAME/docker-react npm run test -- --coverage
 